language: csharp
sudo: required
mono: none
dotnet: 7.0
dist: xenial
script:
  - dotnet restore ./src/
  - dotnet build ./src/
  - dotnet test ./src/Core.Tests/
  - dotnet test ./src/Data.Tests/
  - dotnet test ./src/Http.Tests/
  - dotnet test ./src/Communication.Tests/
  - dotnet test ./src/MediaServer.Core.Tests/
  - dotnet test ./src/MediaServer.Plex.Tests/
  - dotnet test ./src/Security.OAuth.Tests/
  - dotnet pack ./src/Core/Core.csproj /p:NuspecFile=./FrostAura.Libraries.Core.nuspec --version-suffix "$TRAVIS_BUILD_NUMBER" -o "$TRAVIS_BUILD_DIR" -c Release --include-symbols -p:SymbolPackageFormat=snupkg
  - dotnet pack ./src/Data/Data.csproj /p:NuspecFile=./FrostAura.Libraries.Data.nuspec --version-suffix "$TRAVIS_BUILD_NUMBER" -o "$TRAVIS_BUILD_DIR" -c Release --include-symbols -p:SymbolPackageFormat=snupkg
  - dotnet pack ./src/Http/Http.csproj /p:NuspecFile=./FrostAura.Libraries.Http.nuspec --version-suffix "$TRAVIS_BUILD_NUMBER" -o "$TRAVIS_BUILD_DIR" -c Release --include-symbols -p:SymbolPackageFormat=snupkg
  - dotnet pack ./src/Communication/Communication.csproj /p:NuspecFile=./FrostAura.Libraries.Communication.nuspec --version-suffix "$TRAVIS_BUILD_NUMBER" -o "$TRAVIS_BUILD_DIR" -c Release --include-symbols -p:SymbolPackageFormat=snupkg
  - dotnet pack ./src/MediaServer.Core/MediaServer.Core.csproj /p:NuspecFile=./FrostAura.Libraries.MediaServer.Core.nuspec --version-suffix "$TRAVIS_BUILD_NUMBER" -o "$TRAVIS_BUILD_DIR" -c Release --include-symbols -p:SymbolPackageFormat=snupkg
  - dotnet pack ./src/MediaServer.Plex/MediaServer.Plex.csproj /p:NuspecFile=./FrostAura.Libraries.MediaServer.Plex.nuspec --version-suffix "$TRAVIS_BUILD_NUMBER" -o "$TRAVIS_BUILD_DIR" -c Release --include-symbols -p:SymbolPackageFormat=snupkg
  - dotnet pack ./src/Security.OAuth/Security.OAuth.csproj /p:NuspecFile=./FrostAura.Libraries.Security.OAuth.nuspec --version-suffix "$TRAVIS_BUILD_NUMBER" -o "$TRAVIS_BUILD_DIR" -c Release --include-symbols -p:SymbolPackageFormat=snupkg
deploy:
  skip_cleanup: true
  provider: script
  script: cd $TRAVIS_BUILD_DIR & ls & (dotnet nuget push "$TRAVIS_BUILD_DIR/*.nupkg" -k $NUGET_API_KEY -s $NUGET_SOURCE) || true
  on:
    branch: master
