name: NuGet Workflow
on:
  push:
    branches:
    - main
    - master
env:
  DOTNET_VERSION: '7.0.x'
  OUT_DIR: 'release'
jobs:
  build-nuget-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install Dependencies
      run: dotnet restore src/
    - name: Build
      run: dotnet build src/ --configuration Release --no-restore
    - name: Test Core
      run: dotnet test src/Core.Tests/ --no-restore --verbosity normal
    - name: Pack Core
      run: dotnet pack src/Core/Core.csproj /p:NuspecFile=./FrostAura.Libraries.Core.nuspec --version-suffix "${{ github.run_id }}" -o "$OUT_DIR" -c Release --include-symbols -p:SymbolPackageFormat=snupkg
    - name: Test Data
      run: dotnet test src/Data.Tests/ --no-restore --verbosity normal
    - name: Pack Data
      run: dotnet pack src/Data/Data.csproj /p:NuspecFile=./FrostAura.Libraries.Data.nuspec --version-suffix "${{ github.run_id }}" -o "$OUT_DIR" -c Release --include-symbols -p:SymbolPackageFormat=snupkg
    - name: Test Finance
      run: dotnet test src/Finance.Tests/ --no-restore --verbosity normal
    - name: Pack Finance
      run: dotnet pack src/Finance/Finance.csproj /p:NuspecFile=./FrostAura.Libraries.Finance.nuspec --version-suffix "${{ github.run_id }}" -o "$OUT_DIR" -c Release --include-symbols -p:SymbolPackageFormat=snupkg
    - name: Test Http
      run: dotnet test src/Http.Tests/ --no-restore --verbosity normal
    - name: Pack Http
      run: dotnet pack src/Http/Http.csproj /p:NuspecFile=./FrostAura.Libraries.Http.nuspec --version-suffix "${{ github.run_id }}" -o "$OUT_DIR" -c Release --include-symbols -p:SymbolPackageFormat=snupkg
    - name: Test Communication
      run: dotnet test src/Communication.Tests/ --no-restore --verbosity normal
    - name: Pack Communication
      run: dotnet pack src/Communication/Communication.csproj /p:NuspecFile=./FrostAura.Libraries.Communication.nuspec --version-suffix "${{ github.run_id }}" -o "$OUT_DIR" -c Release --include-symbols -p:SymbolPackageFormat=snupkg
    - name: Test Security.OAuth
      run: dotnet test src/Security.OAuth.Tests/ --no-restore --verbosity normal
    - name: Pack Security.OAuth
      run: dotnet pack src/Security.OAuth/Security.OAuth.csproj /p:NuspecFile=./FrostAura.Libraries.Security.OAuth.nuspec --version-suffix "${{ github.run_id }}" -o "$OUT_DIR" -c Release --include-symbols -p:SymbolPackageFormat=snupkg
    - name: Pack Semantic.Core
      run: dotnet pack src/Semantic.Core/Semantic.Core.csproj /p:NuspecFile=./FrostAura.Libraries.Intelligence.Semantic.Core.nuspec --version-suffix "${{ github.run_id }}" -o "$OUT_DIR" -c Release --include-symbols -p:SymbolPackageFormat=snupkg
    - name: Publish NuGet Packages
      run: dotnet nuget push "$OUT_DIR/*.nupkg" -k "${{ secrets.NUGET_API_KEY }}" -s "https://api.nuget.org/v3/index.json" --skip-duplicate